In [42]:
import pandas as pd
from pathlib import Path

csv_path = Path(
    r"C:\Users\sanja\OneDrive\Desktop\GIT FOLDER\Logistics-Data-Pipeline\Data\Raw\DataCoSupplyChainDataset.csv"
)

print("File exists:", csv_path.exists())

File exists: True

In [43]:
df = pd.read_csv(csv_path, encoding="latin1")

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

display(df.head())

Dataset loaded successfully!
Rows: 180519
Columns: 53

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [44]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 180519
Number of columns: 53

In [45]:
print("Column names:")

for col in df.columns:
    print(col)

Column names:
Type
Days for shipping (real)
Days for shipment (scheduled)
Benefit per order
Sales per customer
Delivery Status
Late_delivery_risk
Category Id
Category Name
Customer City
Customer Country
Customer Email
Customer Fname
Customer Id
Customer Lname
Customer Password
Customer Segment
Customer State
Customer Street
Customer Zipcode
Department Id
Department Name
Latitude
Longitude
Market
Order City
Order Country
Order Customer Id
order date (DateOrders)
Order Id
Order Item Cardprod Id
Order Item Discount
Order Item Discount Rate
Order Item Id
Order Item Product Price
Order Item Profit Ratio
Order Item Quantity
Sales
Order Item Total
Order Profit Per Order
Order Region
Order State
Order Status
Order Zipcode
Product Card Id
Product Category Id
Product Description
Product Image
Product Name
Product Price
Product Status
shipping date (DateOrders)
Shipping Mode

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Email                 180519 non-null  str
 12  Customer Fname                 180519 non-null  str
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  str
 15  Customer Password              180519 non-null  str
 16  Customer Segment               180519 non-null  str
 17  Customer State                 180519 non-null  str
 18  Customer Street                180519 non-null  str
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order City                     180519 non-null  str
 26  Order Country                  180519 non-null  str
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  str
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  str
 41  Order State                    180519 non-null  str
 42  Order Status                   180519 non-null  str
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  str
 48  Product Name                   180519 non-null  str
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  str
 52  Shipping Mode                  180519 non-null  str
dtypes: float64(15), int64(14), str(24)
memory usage: 128.3 MB

In [47]:
display(df.head())

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [48]:
display(df.head())

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [49]:
import pandas as pd

missing = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": (
        df.isnull().mean() * 100
    ).round(2)
})

display(
    missing[missing["Missing Count"] > 0]
       .sort_values("Missing Count", ascending=False)
)

                     Missing Count  Missing Percentage
Product Description         180519              100.00
Order Zipcode               155679               86.24
Customer Lname                   8                0.00
Customer Zipcode                 3                0.00

In [50]:
print("Total rows:", len(df))

print("Unique order IDs:",
      df["Order Id"].nunique())

print("Unique order-item IDs:",
      df["Order Item Id"].nunique())

print("Duplicate complete rows:",
      df.duplicated().sum())

print("Duplicate order-item IDs:",
      df["Order Item Id"].duplicated().sum())

Total rows: 180519
Unique order IDs: 65752
Unique order-item IDs: 180519
Duplicate complete rows: 0
Duplicate order-item IDs: 0

In [51]:
date_columns = [
    "order date (DateOrders)",
    "shipping date (DateOrders)"
]

for column in date_columns:
    print(f"\n{column}")
    print(df[column].head(5).to_string(index=False))

order date (DateOrders)
1/31/2018 22:56
1/13/2018 12:27
1/13/2018 12:06
1/13/2018 11:45
1/13/2018 11:24

shipping date (DateOrders)
 2/3/2018 22:56
1/18/2018 12:27
1/17/2018 12:06
1/16/2018 11:45
1/15/2018 11:24

In [52]:
date_columns = [
    "order date (DateOrders)",
    "shipping date (DateOrders)"
]

for column in date_columns:
    df[column] = pd.to_datetime(
        df[column],
        format="%m/%d/%Y %H:%M",
        errors="coerce"
    )

print(df[date_columns].dtypes)

display(df[date_columns].head())

order date (DateOrders)       datetime64[us]
shipping date (DateOrders)    datetime64[us]
dtype: object

  order date (DateOrders) shipping date (DateOrders)
0     2018-01-31 22:56:00        2018-02-03 22:56:00
1     2018-01-13 12:27:00        2018-01-18 12:27:00
2     2018-01-13 12:06:00        2018-01-17 12:06:00
3     2018-01-13 11:45:00        2018-01-16 11:45:00
4     2018-01-13 11:24:00        2018-01-15 11:24:00

In [53]:
for column in date_columns:
    print(f"\nColumn: {column}")
    print("Missing dates:", df[column].isna().sum())
    print("Earliest date:", df[column].min())
    print("Latest date:", df[column].max())

Column: order date (DateOrders)
Missing dates: 0
Earliest date: 2015-01-01 00:00:00
Latest date: 2018-01-31 23:38:00

Column: shipping date (DateOrders)
Missing dates: 0
Earliest date: 2015-01-03 00:00:00
Latest date: 2018-02-06 22:14:00

In [54]:
df["Calculated Shipping Days"] = (
    df["shipping date (DateOrders)"]
    - df["order date (DateOrders)"]
).dt.total_seconds() / 86400

print("Calculated shipping duration:")
display(df["Calculated Shipping Days"].describe())

print("\nRecorded actual shipping days:")
display(df["Days for shipping (real)"].describe())

print("\nScheduled shipping days:")
display(df["Days for shipment (scheduled)"].describe())

Calculated shipping duration:

count    180519.000000
mean          3.498826
std           1.617394
min           0.500000
25%           2.000000
50%           3.000000
75%           5.000000
max           6.000000
Name: Calculated Shipping Days, dtype: float64

Recorded actual shipping days:

count    180519.000000
mean          3.497654
std           1.623722
min           0.000000
25%           2.000000
50%           3.000000
75%           5.000000
max           6.000000
Name: Days for shipping (real), dtype: float64

Scheduled shipping days:

count    180519.000000
mean          2.931847
std           1.374449
min           0.000000
25%           2.000000
50%           4.000000
75%           4.000000
max           4.000000
Name: Days for shipment (scheduled), dtype: float64

In [55]:
print("Recorded actual shipping days:")
display(df["Days for shipping (real)"].describe())

print("Scheduled shipping days:")
display(df["Days for shipment (scheduled)"].describe())

print("Calculated shipping days:")
display(df["Calculated Shipping Days"].describe())

Recorded actual shipping days:

count    180519.000000
mean          3.497654
std           1.623722
min           0.000000
25%           2.000000
50%           3.000000
75%           5.000000
max           6.000000
Name: Days for shipping (real), dtype: float64

Scheduled shipping days:

count    180519.000000
mean          2.931847
std           1.374449
min           0.000000
25%           2.000000
50%           4.000000
75%           4.000000
max           4.000000
Name: Days for shipment (scheduled), dtype: float64

Calculated shipping days:

count    180519.000000
mean          3.498826
std           1.617394
min           0.500000
25%           2.000000
50%           3.000000
75%           5.000000
max           6.000000
Name: Calculated Shipping Days, dtype: float64

In [56]:
print(
    "Rows where calculated duration differs "
    "from recorded actual days:",
    (
        df["Calculated Shipping Days"]
        != df["Days for shipping (real)"]
    ).sum()
)

Rows where calculated duration differs from recorded actual days: 9737

In [57]:
display(df["Days for shipment (scheduled)"].describe())

count    180519.000000
mean          2.931847
std           1.374449
min           0.000000
25%           2.000000
50%           4.000000
75%           4.000000
max           4.000000
Name: Days for shipment (scheduled), dtype: float64

In [58]:
mismatch = (
    df["Calculated Shipping Days"].round(6)
    != df["Days for shipping (real)"]
)

print("Rows with differing durations:", mismatch.sum())
print("Percentage differing:", round(mismatch.mean() * 100, 2), "%")

display(
    df.loc[
        mismatch,
        [
            "order date (DateOrders)",
            "shipping date (DateOrders)",
            "Calculated Shipping Days",
            "Days for shipping (real)",
            "Days for shipment (scheduled)"
        ]
    ].head(10)
)

Rows with differing durations: 9737
Percentage differing: 5.39 %

,order date (DateOrders),shipping date (DateOrders),Calculated Shipping Days,Days for shipping (real),Days for shipment (scheduled)
19,2018-01-13 06:09:00,2018-01-13 18:09:00,0.5,0,0
20,2018-01-13 05:48:00,2018-01-13 17:48:00,0.5,0,0
38,2018-01-12 23:30:00,2018-01-13 11:30:00,0.5,1,0
39,2018-01-12 23:09:00,2018-01-13 11:09:00,0.5,1,0
40,2018-01-12 22:48:00,2018-01-13 10:48:00,0.5,1,0
41,2018-01-12 22:27:00,2018-01-13 10:27:00,0.5,1,0
387,2018-01-12 11:14:00,2018-01-12 23:14:00,0.5,0,0
388,2018-01-12 10:53:00,2018-01-12 22:53:00,0.5,0,0
389,2018-01-12 10:32:00,2018-01-12 22:32:00,0.5,0,0
447,2018-01-11 14:13:00,2018-01-12 02:13:00,0.5,1,0

In [59]:
df["Calculated Calendar Days"] = (
    df["shipping date (DateOrders)"].dt.normalize()
    - df["order date (DateOrders)"].dt.normalize()
).dt.days

calendar_mismatch = (
    df["Calculated Calendar Days"]
    != df["Days for shipping (real)"]
)

print(
    "Calendar-day mismatches:",
    calendar_mismatch.sum()
)

print(
    "Calendar-day mismatch percentage:",
    round(calendar_mismatch.mean() * 100, 2),
    "%"
)

display(
    df.loc[
        calendar_mismatch,
        [
            "order date (DateOrders)",
            "shipping date (DateOrders)",
            "Calculated Calendar Days",
            "Days for shipping (real)"
        ]
    ].head(10)
)

Calendar-day mismatches: 0
Calendar-day mismatch percentage: 0.0 %

Empty DataFrame
Columns: [order date (DateOrders), shipping date (DateOrders), Calculated Calendar Days, Days for shipping (real)]
Index: []

In [60]:
print("Delivery status counts:")
display(df["Delivery Status"].value_counts())

print("\nLate delivery risk counts:")
display(df["Late_delivery_risk"].value_counts())

print("\nScheduled shipping days:")
display(df["Days for shipment (scheduled)"].value_counts().sort_index())

print("\nActual shipping days:")
display(df["Days for shipping (real)"].value_counts().sort_index())

Delivery status counts:

Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

Late delivery risk counts:

Late_delivery_risk
1    98977
0    81542
Name: count, dtype: int64

Scheduled shipping days:

Days for shipment (scheduled)
0      9737
1     27814
2     35216
4    107752
Name: count, dtype: int64

Actual shipping days:

Days for shipping (real)
0     5080
1     4657
2    56618
3    28765
4    28513
5    28163
6    28723
Name: count, dtype: int64

In [61]:
risk_check = pd.crosstab(
    df["Delivery Status"],
    df["Late_delivery_risk"],
    margins=True
)

display(risk_check)

Late_delivery_risk      0      1     All
Delivery Status
Advance shipping    41592      0   41592
Late delivery           0  98977   98977
Shipping canceled    7754      0    7754
Shipping on time    32196      0   32196
All                 81542  98977  180519

In [62]:
expected_risk = (
    df["Delivery Status"] == "Late delivery"
).astype(int)

mismatches = (
    df["Late_delivery_risk"] != expected_risk
).sum()

print("Delivery status/risk mismatches:", mismatches)

Delivery status/risk mismatches: 0

In [63]:
print("Shipping mode:")
display(df["Shipping Mode"].value_counts())

print("\nOrder status:")
display(df["Order Status"].value_counts())

Shipping mode:

Shipping Mode
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: count, dtype: int64

Order status:

Order Status
COMPLETE           59491
PENDING_PAYMENT    39832
PROCESSING         21902
PENDING            20227
CLOSED             19616
ON_HOLD             9804
SUSPECTED_FRAUD     4062
CANCELED            3692
PAYMENT_REVIEW      1893
Name: count, dtype: int64

In [64]:
numeric_columns = [
    "Sales",
    "Order Profit Per Order",
    "Days for shipping (real)",
    "Days for shipment (scheduled)"
]

display(df[numeric_columns].describe().T)

,count,mean,std,min,25%,50%,75%,max
Sales,180519.0,203.772096,132.273077,9.99000,119.980003,199.919998,299.950012,1999.989990
Order Profit Per Order,180519.0,21.974989,104.433526,-4274.97998,7.000000,31.520000,64.800003,911.799988
Days for shipping (real),180519.0,3.497654,1.623722,0.00000,2.000000,3.000000,5.000000,6.000000
Days for shipment (scheduled),180519.0,2.931847,1.374449,0.00000,2.000000,4.000000,4.000000,4.000000

In [65]:
print(
    "Negative profit rows:",
    (df["Order Profit Per Order"] < 0).sum()
)

print(
    "Zero or negative sales rows:",
    (df["Sales"] <= 0).sum()
)

Negative profit rows: 33784
Zero or negative sales rows: 0

In [66]:
delivery_check = pd.crosstab(
    df["Shipping Mode"],
    df["Delivery Status"]
)

display(delivery_check)

Delivery Status,Advance shipping,Late delivery,Shipping canceled,Shipping on time
Shipping Mode,,,,
First Class,0,26513,1301,0
Same Day,0,4454,444,4839
Second Class,0,26987,1410,6819
Standard Class,41592,41023,4599,20538

In [67]:
delivery_percentages = pd.crosstab(
    df["Shipping Mode"],
    df["Delivery Status"],
    normalize="index"
) * 100

display(delivery_percentages.round(2))

Delivery Status,Advance shipping,Late delivery,Shipping canceled,Shipping on time
Shipping Mode,,,,
First Class,0.0,95.32,4.68,0.00
Same Day,0.0,45.74,4.56,49.70
Second Class,0.0,76.63,4.00,19.36
Standard Class,38.6,38.07,4.27,19.06

In [68]:
shipping_comparison = df.groupby(
    "Days for shipment (scheduled)"
).agg(
    Total_Rows=("Order Item Id", "count"),
    Average_Actual_Days=("Days for shipping (real)", "mean")
)

display(shipping_comparison.round(2))

                               Total_Rows  Average_Actual_Days
Days for shipment (scheduled)
0                                    9737                 0.48
1                                   27814                 2.00
2                                   35216                 3.99
4                                  107752                 4.00

In [69]:
important_columns = [
    "Order Id",
    "Order Item Id",
    "order date (DateOrders)",
    "shipping date (DateOrders)",
    "Customer Id",
    "Product Card Id",
    "Sales",
    "Order Profit Per Order",
    "Shipping Mode",
    "Delivery Status",
    "Days for shipping (real)",
    "Days for shipment (scheduled)"
]

display(df[important_columns].head())

,Order Id,Order Item Id,order date (DateOrders),shipping date (DateOrders),Customer Id,Product Card Id,Sales,Order Profit Per Order,Shipping Mode,Delivery Status,Days for shipping (real),Days for shipment (scheduled)
0,77202,180517,2018-01-31 22:56:00,2018-02-03 22:56:00,20755,1360,327.75,91.250000,Standard Class,Advance shipping,3,4
1,75939,179254,2018-01-13 12:27:00,2018-01-18 12:27:00,19492,1360,327.75,-249.089996,Standard Class,Late delivery,5,4
2,75938,179253,2018-01-13 12:06:00,2018-01-17 12:06:00,19491,1360,327.75,-247.779999,Standard Class,Shipping on time,4,4
3,75937,179252,2018-01-13 11:45:00,2018-01-16 11:45:00,19490,1360,327.75,22.860001,Standard Class,Advance shipping,3,4
4,75936,179251,2018-01-13 11:24:00,2018-01-15 11:24:00,19489,1360,327.75,134.210007,Standard Class,Advance shipping,2,4

# Phase 2 — Dataset Acquisition and Exploration Summary

## Dataset Overview
- Dataset: DataCo SMART Supply Chain Dataset
- Total rows: 180,519
- Total columns: 53
- Data format: CSV
- Encoding: Latin-1

## Data Quality Findings
- `Product Description` is entirely missing.
- `Order Zipcode` has approximately 86.24% missing values.
- Eight customer last-name values and three customer ZIP-code values are missing.
- No duplicate complete rows were found.
- `Order Item Id` has no duplicate values.
- Both order and shipping date columns were successfully converted to datetime.
- Calendar-day shipping calculations matched `Days for shipping (real)` for all rows.
- All sales values are positive.
- There are 33,784 rows with negative profit, which require business interpretation rather than automatic deletion.

## Business Findings
- 98,977 rows are labeled `Late delivery` (approximately 54.83%).
- Standard Class accounts for the largest number of records.
- Delivery-status percentages differ across shipping modes.
- Average actual shipping time is approximately 3.50 days.

## Important Columns
Order IDs, order-item IDs, customer IDs, product IDs, sales, profit, order dates, shipping dates, shipping modes, delivery status, actual shipping days, and scheduled shipping days.

## Data Privacy
Customer emails and passwords must not be published or included in public reports, exports, or GitHub.

## Phase 2 Conclusion
The dataset has been loaded and explored. Initial data-quality checks and business summaries have been completed. Further cleaning, database design, and transformations will be performed in later phases.